// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnibBOj-5kw11olCIcmPoCswfCwlhTC-Q',
    appId: '1:3961502014:web:df9efcec520893751b546f',
    messagingSenderId: '3961502014',
    projectId: 'chatter-b24dc',
    authDomain: 'chatter-b24dc.firebaseapp.com',
    storageBucket: 'chatter-b24dc.appspot.com',
    measurementId: 'G-JX9VE3D69W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvOkacfW1PjLaA1QAHl8PBxJ1rdwGx1Bs',
    appId: '1:3961502014:android:282df3d6ecf2dbdd1b546f',
    messagingSenderId: '3961502014',
    projectId: 'chatter-b24dc',
    storageBucket: 'chatter-b24dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKLkfe8nLoehAtW59kcAfk3CzdHLRG8XU',
    appId: '1:3961502014:ios:d07a89afb15f784d1b546f',
    messagingSenderId: '3961502014',
    projectId: 'chatter-b24dc',
    storageBucket: 'chatter-b24dc.appspot.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKLkfe8nLoehAtW59kcAfk3CzdHLRG8XU',
    appId: '1:3961502014:ios:d07a89afb15f784d1b546f',
    messagingSenderId: '3961502014',
    projectId: 'chatter-b24dc',
    storageBucket: 'chatter-b24dc.appspot.com',
    iosBundleId: 'com.example.chatter',
  );
}
